[2023-12-11 16:20:30,651] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 16:20:30] "GET /produtos HTTP/1.1" 200 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 16:20:34,275] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 16:20:34] "GET /produtos HTTP/1.1" 200 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 16:20:35,002] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 16:20:35] "GET /produtos HTTP/1.1" 200 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 16:20:37,489] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 16:20:37] "GET /produtos HTTP/1.1" 200 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 16:20:39,004] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 16:20:39] "GET /produtos HTTP/1.1" 200 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 16:20:39,793] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 16:20:39] "GET /produtos HTTP/1.1" 200 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 16:20:40,515] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 16:20:40] "GET /produtos HTTP/1.1" 200 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 16:50:05,001] INFO _log() L96   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 16:50:05,001] INFO _log() L96   [33mPress CTRL+C to quit[0m - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 16:50:11,920] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 16:50:11] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 16:50:12,122] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 16:50:12] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 16:50:13,488] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 16:50:13] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 16:50:13,563] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 16:50:13] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 16:50:13,575] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 16:50:13] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 16:50:14,842] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 16:50:14] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 16:50:14,898] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 16:50:14] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 16:50:15,049] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 16:50:15] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 16:50:15,233] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 16:50:15] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 16:50:16,342] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 16:50:16] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 16:50:16,514] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 16:50:16] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 16:51:00,934] WARNING del_produto() L135  Erro ao deletar produto #'cerveja', Produto não encontrado na base :/ - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\app.py L135 
[2023-12-11 16:51:00,934] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 16:51:00] "[33mDELETE /produto?nome=cerveja HTTP/1.1[0m" 404 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 16:51:41,891] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 16:51:41] "DELETE /produto?nome=vodka HTTP/1.1" 200 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 16:54:48,066] ERROR log_exception() L825  Exception on /produto [GET] - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask\app.py L825 
Traceback (most recent call last):
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\app.py", line 94, in get_produto
    produto_id = query.id
                 ^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\pydantic\main.py", line 761, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'ProdutoBuscaSchema' object has no attribute 'id'
[2023-12-11 16:54:48,093] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 16:54:48] "[35m[1mGET /produto?nome=cerveja HTTP/1.1[0m" 500 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
[2023-12-11 16:55:04,561] ERROR log_exception() L825  Exception on /produto [GET] - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask\app.py L825 
Traceback (most recent call last):
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\app.py", line 94, in get_produto
    produto_id = query.id
                 ^^^^^^^^
  File "C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\pydantic\main.py", line 761, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'ProdutoBuscaSchema' object has no attribute 'id'
[2023-12-11 16:55:04,574] INFO _log() L96   127.0.0.1 - - [11/Dec/2023 16:55:04] "[35m[1mGET /produto?nome=água HTTP/1.1[0m" 500 - - call_trace=C:\Users\teste\Desktop\projeto\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L96  
